name: build-dist
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install && yarn build
      - run: find {popup,scripts} -maxdepth 1 -mindepth 1 ! -name 'dist' -exec rm -fr {} +
      - run: rm -fr .github package.json yarn.lock
      - run: |
          git config user.name Sherly1001
          git config user.email Sherly1001@users.noreply.github.com
          git checkout -b dist
          git add .
          git add -f {popup,scripts}/dist
          git rm .gitignore
          git commit -m 'update build'
          git push -f origin dist
